Contato/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('detalhes/<int:id>/', views.contato_detalhes, name='contato_detalhe'),
    path('contato/', views.index, name='contato'),
    path('contato/cadastro/', views.contatoform, name='contatoform'),
    path('ver_imagem/', views.ver_imagem, name='ver_imagem'),

]

account/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),

]

agenda/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Contato.urls')),
    path('', include('account.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Contato/models.py
from django.db import models

# Create your models here.
from django.db import models


class Contato(models.Model):
    nome = models.CharField(max_length=255)
    Categoria = models.ForeignKey('Categoria', on_delete=models.CASCADE)
    foto = models.ImageField(blank=True, null=True)
    email = models.EmailField(unique=True)
    telefone = models.CharField(max_length=20)
    endereco = models.CharField(max_length=255)
    cep = models.CharField(max_length=9)
    cidade = models.CharField(max_length=100)
    estado = models.CharField(max_length=50)
    data_criacao = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nome


class Categoria(models.Model):
    nome = models.CharField(max_length=255)

    def __str__(self):
        return self.nome

account/models.py
from django.db import models

# Create your models here.

Contato/views.py
from django.shortcuts import render
from .models import Contato, Categoria
from django.views.generic import ListView
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
# Create your views here.


@login_required(login_url='login')
def index(request):
    contatos = Contato.objects.all()
    categorias = Categoria.objects.all()
    return render(request, 'pages/index.html', {'contatos': contatos, 'categorias': categorias})


# class ContatoListView(ListView):
 #   model = Contato
  #  template_name = 'pages/index.html'
    # context_object_name = 'contatos'

@login_required(login_url='login')
def contato_detalhes(request, id):
    # contato = Contato.objects.get(id=id)
    # , {'contato': contato})
    return render(request, 'pages/contato_detalhes.html', {'contato': Contato.objects.get(id=id)})


def home(request):
    contatos = Contato.objects.all()
    return render(request, 'pages/home.html', {'contatos': contatos})
#    return render(request, 'pages/home.html')


@login_required(login_url='login')
def contatoform(request):
    categoria = Categoria.objects.all()
    if request.method == 'POST':
        nome = request.POST['nome']
        email = request.POST['email']
        foto = request.FILES['foto']
        telefone = request.POST['telefone']
        cep = request.POST['cep']
        cidade = request.POST['cidade']
        estado = request.POST['estado']
        categoria = request.POST['categoria']

        contato = Contato(nome=nome, email=email, foto=foto, telefone=telefone,
                          cep=cep, cidade=cidade, estado=estado, Categoria_id=categoria)
        contato.save()
        print(contato)
        return HttpResponse('Contato cadastrado com sucesso!')

    else:
        categoria = Categoria.objects.all()
        return render(request, 'pages/contatoform.html', {'categorias': categoria})


def ver_imagem(request):
    contatos = Contato.objects.all()
    return render(request, 'pages/ver_imagem.html', {'contatos': contatos})

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth, messages
# Create your views here.


def login(request):
    if request.method == "POST":

        usuario = request.POST['usuario']
        senha = request.POST['senha']

        verificar_usuario = auth.authenticate(username=usuario, password=senha)

        if verificar_usuario != None:
            auth.login(request, verificar_usuario)

            return redirect('home')

        else:
            print("Usuario ou senha invalidos")

    return render(request, 'pages/login.html')


def logout(request):
    auth.logout(request)
    return redirect('home')


def register(request):

    if request.method == "POST":
        usuario = request.POST['usuario']
        email = request.POST['email']
        senha = request.POST['senha']
        confirmar_senha = request.POST['confirmar_senha']

        if User.objects.filter(username=usuario).exists():
            messages.error(
                request, "Nome de usuário já existe. Escolha outro.")
            return redirect('register')

        User.objects.create_user(username=usuario, email=email, password=senha)
        messages.success(request, "Usuário criado com sucesso!")
        return redirect('login')

    else:
        return render(request, 'pages/register.html')

Contato/templates/pages/contato_detalhes.html
<!-- {% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style.css' %}" />
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-6 offset-md-3">
          <h1>Contato</h1>
          <form action="{% url 'contato' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
              <label for="id_nome">Nome</label>
              <input
                type="text"
                name="nome"
                id="id_nome"
                class="form-control"
              />
            </div>
            <div class="form-group">
              <label for="id_email">E-mail</label>
              <input
                type="email"
                name="email"
                id="id_email"
                class="form-control"
              />
            </div>
            <div class="form-group">
              <label for="id_mensagem">Mensagem</label>
              <textarea
                name="mensagem"
                id="id_mensagem"
                class="form-control"
              ></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Enviar</button>
          </form>
        </div>
      </div>
    </div>
  </body>
</html> -->

{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    
    <header>
      <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #77d377; opacity: 0.9;">
        <h3 class="mr-auto">{{ request.user }}</h3>
        <a class="navbar-brand ml-3" href="{% url 'home' %}">Contato</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contato' %}">Contatos</a>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
            {% if not request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            {% endif %} {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Sair</a>
            </li>
            {% endif %}
      </div>
      </nav>
    </header>
    <div class="container mt-5 justify-content-center align-items-center;" style=background-color:#77d377;>
      <div>
      <h2 class="text-center">Contato Selecionado</h2>
      <table class="table table-striped">
        <thead>
        <tr>
          <th>Foto</th>
          <th>Nome</th>
          <th>Email</th>
          <th>Telefone</th>
          <th>Endereço</th>
          <th>CEP</th>
          <th>Cidade</th>
          <th>Estado</th>
          <th>Data de Criação</th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <tr>
          {% if contato.foto %}
          <!-- <td>{{ contato.foto.url }}</td> --><td>
          <img src="{{ contato.foto.url }}" alt="Imagem do Contato" class="img-fluid rounded-circle" style="max-width: 30%; height: auto;" /> <!-- event click na imagem para expandir na própria tela-->
          </td>
          {% else %}
          {% endif %}
          <td>{{ contato.nome }}</td>
          <td>{{ contato.email }}</td>
          <td>{{ contato.telefone }}</td>
          <td>{{ contato.endereco }}</td>
          <td>{{ contato.cep }}</td>
          <td>{{ contato.cidade }}</td>
          <td>{{ contato.estado }}</td>
          <td>{{ contato.data_criacao|date:"d/m/Y" }}</td>
        </tbody>
      </table>
      </div>
    </div>
    </div>
  </body>
</html>

Contato/templates/pages/contatoform.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    <header>
      <nav
        class="navbar navbar-expand-lg navbar-light"
        style="background-color: #77d377; opacity: 0.9"
      >
        <h3 class="mr-auto">{{ request.user }}</h3>
        <a class="navbar-brand ml-3" href="{% url 'home' %}">Contato</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contato' %}">Contatos</a>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
            {% if not request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            {% endif %} {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Sair</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <div class="container mt-5" style="background-color: #77d377">
      <h2 class="text-center">Formulário de Contato</h2>
      <form
        action="{% url 'contatoform' %}"
        method="POST"
        class="form-signin"
        enctype="multipart/form-data"
      >
        {% csrf_token %}
        <label for="inputNome" class="sr-only">Nome</label>
        <input
          type="text"
          id="inputNome"
          name="nome"
          class="form-control"
          placeholder="Nome"
          required
          autofocus
        />
        <label for="inputEmail" class="sr-only">Email</label>
        <input
          type="email"
          id="inputEmail"
          name="email"
          class="form-control"
          placeholder="Email"
          required
        />
        <label for="inputFoto" class="sr-only">Foto</label>
        <input
          type="file"
          id="inputFoto"
          name="foto"
          class="form-control"
          placeholder="Foto"
          required
        />
        <label for="inputTelefone" class="sr-only">Telefone</label>
        <input
          type="text"
          id="inputTelefone"
          name="telefone"
          class="form-control"
          placeholder="Telefone"
          required
        />
        <label for="inputEndereco" class="sr-only">Endereço</label>
        <input
          type="text"
          id="inputEndereco"
          name="endereco"
          class="form-control"
          placeholder="Endereço"
          required
        />
        <label for="inputCep" class="sr-only">CEP</label>
        <input
          type="text"
          id="inputCep"
          name="cep"
          class="form-control"
          placeholder="CEP"
          required
        />
        <label for="inputCidade" class="sr-only">Cidade</label>
        <input
          type="text"
          id="inputCidade"
          name="cidade"
          class="form-control"
          placeholder="Cidade"
          required
        />
        <label for="inputEstado" class="sr-only">Estado</label>
        <input
          type="text"
          id="inputEstado"
          name="estado"
          class="form-control"
          placeholder="Estado"
          required
        />
        <label for="inputCategoria" class="sr-only">Categoria</label>
        <select
          id="inputCategoria"
          name="categoria"
          class="form-control"
          required
        >
          <option value="" disabled selected>Selecione uma categoria</option>
          {% for categoria in categorias %}
          <option value="{{ categoria.id }}">{{ categoria.nome }}</option>
          {% endfor %}
        </select>
        <button type="submit" class="btn btn-primary">Enviar</button>
      </form>
    </div>
  </body>
</html>

Contato/templates/pages/home.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    <header>
      <nav
        class="navbar navbar-expand-lg navbar-light"
        style="background-color: #77d377; opacity: 0.9"
      >
        <h3 class="mr-auto">{{ request.user }}</h3>
        <a class="navbar-brand ml-3" href="{% url 'home' %}">Contato</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contato' %}">Contatos</a>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
            {% if not request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            {% endif %} {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Sair</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <div class="container mt-5" style="background-color: #77d377">
      <h1 class="text-center">Seja Bem Vindo</h1>
      <p class="description" style="text-align: center">
        Clique em Contatos para visualizar a lista de contatos cadastrados:
      </p>
      <nav class="navigation" style="text-align: center">
        <ul>
          <li><a href="{% url 'contato' %}">Contatos</a></li>
        </ul>
      </nav>
    </div>
  </body>
</html>

Contato/templates/pages/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    <header>
      <nav
        class="navbar navbar-expand-lg navbar-light"
        style="background-color: #77d377; opacity: 0.9"
      >
      <h3 class="mr-auto">{{ request.user }}</h3>
      <a class="navbar-brand ml-3" href="{% url 'home' %}">Contato</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contato' %}">Contatos</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if not request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          {% endif %} {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Sair</a>
          </li>
          {% endif %}
        </div>
      </nav>
    </header>
    <div class="container mt-5" style="background-color: #77d377">
        <div class="d-flex justify-content-between">
      <h2 class="text-center justify-content-center">Lista de Contatos</h2>
      <a href="{% url 'contatoform' %}" class="flex justify-content-end btn btn-primary mb-1 btn-lg btn-success">+</a>
      </div>
      <div class="d-flex justify-content-center">        
        <table class="table table-striped w-75">
          <thead>
            <tr>
              <th class="text-center">Nome do Contato</th>
              <th class="text-center">Data de Criação</th>
            </tr>
          </thead>
          <tbody>
            {% for contato in contatos %}
            <tr>
              <td class="text-center">
                <a href="{% url 'contato_detalhe' contato.id %}"
                  >{{ contato.nome }}</a
                >
              </td>
              <td class="text-center">{{ contato.data_criacao }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <div class="container mt-5" style="background-color: #77d377">
      <h2 class="text-center">Lista de Categorias</h2>
      <div class="d-flex justify-content-center">
        <table class="table table-striped w-75">
          <thead>
            <tr>
              <th class="text-center">Nome da Categoria</th>
            </tr>
          </thead>
          <tbody>
            {% for categoria in categorias %}
            <tr>
              <td class="text-center">{{ categoria.nome }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </body>
</html>

Contato/templates/pages/ver_imagem.html
<!DOCTYPE html>
<html lang="pt-br">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>Document</title>
  </head>
  <body>
    <header>
        <nav
          class="navbar navbar-expand-lg navbar-light"
          style="background-color: #77d377; opacity: 0.9"
        >
        <h3 class="mr-auto">{{ request.user }}</h3>
        <a class="navbar-brand ml-3" href="{% url 'home' %}">Contato</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contato' %}">Contatos</a>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
            {% if not request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            {% endif %} {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Sair</a>
            </li>
            {% endif %}
          </div>
        </nav>
      </header>
    <h1 class="text-center">Visualizar Imagem</h1>
    <div class="container mt-3" style="background-color: #77d377;">
      {% for contato in contatos %}

        {% if contato.foto %}
      <img src="{{ contato.foto.url }}" alt="Imagem do Contato" class="img-fluid rounded-circle" style="max-width: 100%; height: auto;" />
        {% endif %}
      {% endfor %}
    </div>
    <div class="d-flex justify-content-center mt-3 mb-3">
      <a href="{% url 'contato' %}" class="btn btn-primary">Voltar</a>    
  </body>
</html>

account/templates/pages/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <title>Document</title>
  </head>
  <body>
    <form
      action="{% url 'login' %}"
      method="POST"
      style="display: flex; flex-direction: column; width: 300px; margin: auto"
    >
      {% csrf_token %}
      <h1 style="text-align: center">Login</h1>
      <input type="text" name="usuario" placeholder="Usuário" />
      <input type="password" name="senha" placeholder="Senha" />
      <button type="submit">Entrar</button>
    </form>
  </body>
</html>

account/templates/pages/register.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <title>Register</title>
  </head>
  <body>
    <div class="container mt-5 justify-content-center align-items-center;">
      <div class="row justify-content-center">
        <div class="col-md-6">
          <form action="{% url 'register' %}" method="POST" class="form-signin">
            {% csrf_token %}
            <h1 class="h3 mb-3 font-weight-normal text-center">Register</h1>
            <label for="inputUsuario" class="sr-only">Usuário</label>
            <input
              type="text"
              id="inputUsuario"
              name="usuario"
              class="form-control"
              placeholder="Usuário"
              required
              autofocus
            />
            <label for="inputEmail" class="sr-only">E-mail</label>
            <input
              type="email"
              id="inputEmail"
              name="email"
              class="form-control"
              placeholder="E-mail"
              required
            />
            <label for="inputSenha" class="sr-only">Senha</label>
            <input
              type="password"
              id="inputSenha"
              name="senha"
              class="form-control"
              placeholder="Senha"
              required
            />
            <label for="inputConfirmarSenha" class="sr-only"
              >Confirme a senha</label
            >
            <input
              type="password"
              id="inputConfirmarSenha"
              name="confirmar_senha"
              class="form-control"
              placeholder="Confirme a senha"
              required
            />
            <button class="btn btn-lg btn-primary btn-block" type="submit">
              Cadastrar
            </button>
            <a href="{% url 'login' %}" class="btn btn-link btn-block">Login</a>
          </form>
        </div>
      </div>
    </div>
    {% if messages %} {% for message in messages %}
    <div
      class="alert alert-danger"
      style="
        text-align: center;
        margin-top: 10px;
        color: red;
        font-weight: bold;
      "
    >
      {{ message }}
    </div>
    {% endfor %} {% endif %}
  </body>
</html>